---
- hosts: DOCKER

  tasks:

  - name: IMPORT KEY FROM URL
    apt_key:
      state: present
      url: '{{ item }}'
    with_items:
      - https://download.docker.com/linux/ubuntu/gpg


  - name: ADD REPOSITORY TO APT
    apt_repository:
      repo: '{{ item }}'
      state: present
    with_items:
      - deb [arch=amd64] https://download.docker.com/linux/ubuntu artful stable


#  - name: UPDATE USING APT
#    apt: update_cache=yes


  - name: INSTALL PACKAGES
    become: true
    apt: name={{ item }} state=installed
    with_items:
      - docker-ce


  - name: ENSURE DOCKER STARTED
    service: name=docker state=started
