---
- hosts: DOCKER

  tasks:

  - name: DEFINE PROVIDER
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"


  - name: IMPORT KEY FROM URL
    provider: "{{ provider }}"
    apt_key:
      state: present
      url: '{{ item }}'
    with_items:
      - https://download.docker.com/linux/ubuntu/gpg


  - name: ADD REPOSITORY TO APT
     provider: "{{ provider }}"
    apt_repository:
      repo: '{{ item }}'
      state: present
    with_items:
      - deb [arch=amd64] https://download.docker.com/linux/ubuntu artful stable


#  - name: UPDATE USING APT
#    apt: update_cache=yes


  - name: INSTALL PACKAGES
    provider: "{{ provider }}"
    become: true
    apt: name={{ item }} state=installed
    with_items:
      - docker-ce


  - name: ENSURE DOCKER STARTED
    provider: "{{ provider }}"
    service: name=docker state=started
